


# ALL_SECTIONS = [
#     # ── By area ─────────────────────────────────────────────────────
#     (
#         "sec_maitama",
#         "Luxury Homes in Maitama",
#         f"/properties/?area={m['maitama']}",
#         dict(location__area_id=m["maitama"]),
#         "-views",
#         bool(m["maitama"]),
#     ),
#     (
#         "sec_asokoro_serviced",
#         "Serviced Apartments in Asokoro",
#         f"/properties/?area={m['asokoro']}&serviced=true",
#         dict(location__area_id=m["asokoro"], serviced=True),
#         "-views",
#         bool(m["asokoro"]),
#     ),
#     (
#         "sec_wuse2_flats",
#         "Flats for Rent in Wuse II",
#         f"/properties/?area={m['wuse2']}&property_type={m['flat']}&purpose=rent",
#         dict(location__area_id=m["wuse2"], property_type_id=m["flat"], purpose="rent"),
#         "-views",
#         bool(m["wuse2"] and m["flat"]),
#     ),
#     (
#         "sec_gwarinpa_3bed",
#         "3-Bedroom Homes in Gwarinpa",
#         f"/properties/?area={m['gwarinpa']}&bedrooms=3",
#         dict(location__area_id=m["gwarinpa"], bedrooms=3),
#         "-views",
#         bool(m["gwarinpa"]),
#     ),
#     (
#         "sec_jabi_furnished",
#         "Furnished Apartments in Jabi",
#         f"/properties/?area={m['jabi']}&furnished=true",
#         dict(location__area_id=m["jabi"], furnished=True),
#         "-views",
#         bool(m["jabi"]),
#     ),
#     (
#         "sec_kubwa_budget",
#         "Affordable Rentals in Kubwa",
#         f"/properties/?area={m['kubwa']}&purpose=rent",
#         dict(location__area_id=m["kubwa"], purpose="rent"),
#         "price",
#         bool(m["kubwa"]),
#     ),
#     (
#         "sec_garki",
#         "Properties in Garki",
#         f"/properties/?area={m['garki']}",
#         dict(location__area_id=m["garki"]),
#         "-views",
#         bool(m["garki"]),
#     ),
#     (
#         "sec_utako",
#         "Homes in Utako",
#         f"/properties/?area={m['utako']}",
#         dict(location__area_id=m["utako"]),
#         "-views",
#         bool(m["utako"]),
#     ),
#     (
#         "sec_life_camp",
#         "Life Camp Apartments",
#         f"/properties/?area={m['life_camp']}",
#         dict(location__area_id=m["life_camp"]),
#         "-views",
#         bool(m["life_camp"]),
#     ),
#     (
#         "sec_kado",
#         "Properties in Kado",
#         f"/properties/?area={m['kado']}",
#         dict(location__area_id=m["kado"]),
#         "-views",
#         bool(m["kado"]),
#     ),
#     (
#         "sec_gudu",
#         "Homes in Gudu",
#         f"/properties/?area={m['gudu']}",
#         dict(location__area_id=m["gudu"]),
#         "-views",
#         bool(m["gudu"]),
#     ),
#     (
#         "sec_apo",
#         "Affordable Homes in Apo",
#         f"/properties/?area={m['apo']}",
#         dict(location__area_id=m["apo"]),
#         "price",
#         bool(m["apo"]),
#     ),
#     (
#         "sec_lugbe",
#         "Budget Rentals in Lugbe",
#         f"/properties/?area={m['lugbe']}&purpose=rent",
#         dict(location__area_id=m["lugbe"], purpose="rent"),
#         "price",
#         bool(m["lugbe"]),
#     ),
#     (
#         "sec_lokogoma",
#         "Homes in Lokogoma",
#         f"/properties/?area={m['lokogoma']}",
#         dict(location__area_id=m["lokogoma"]),
#         "-views",
#         bool(m["lokogoma"]),
#     ),
#     (
#         "sec_galadimawa",
#         "Rentals in Galadimawa",
#         f"/properties/?area={m['galadimawa']}&purpose=rent",
#         dict(location__area_id=m["galadimawa"], purpose="rent"),
#         "-views",
#         bool(m["galadimawa"]),
#     ),
#     (
#         "sec_dawaki",
#         "Homes in Dawaki",
#         f"/properties/?area={m['dawaki']}",
#         dict(location__area_id=m["dawaki"]),
#         "-views",
#         bool(m["dawaki"]),
#     ),
#     (
#         "sec_wuse1",
#         "Properties in Wuse I",
#         f"/properties/?area={m['wuse1']}",
#         dict(location__area_id=m["wuse1"]),
#         "-views",
#         bool(m["wuse1"]),
#     ),
#     (
#         "sec_mpape",
#         "Budget Options in Mpape",
#         f"/properties/?area={m['mpape']}&purpose=rent",
#         dict(location__area_id=m["mpape"], purpose="rent"),
#         "price",
#         bool(m["mpape"]),
#     ),
#     # ── By type ──────────────────────────────────────────────────────
#     (
#         "sec_hostels",
#         "Student Hostels across Abuja",
#         f"/properties/?property_type={m['hostel']}",
#         dict(property_type_id=m["hostel"]),
#         "-views",
#         bool(m["hostel"]),
#     ),
#     (
#         "sec_self_contain",
#         "Self-Contain Apartments",
#         f"/properties/?property_type={m['self_contain']}",
#         dict(property_type_id=m["self_contain"]),
#         "-views",
#         bool(m["self_contain"]),
#     ),
#     (
#         "sec_duplexes_sale",
#         "Duplexes for Sale in Abuja",
#         f"/properties/?property_type={m['duplex']}&purpose=sale",
#         dict(property_type_id=m["duplex"], purpose="sale"),
#         "-views",
#         bool(m["duplex"]),
#     ),
#     (
#         "sec_duplexes_rent",
#         "Duplexes for Rent",
#         f"/properties/?property_type={m['duplex']}&purpose=rent",
#         dict(property_type_id=m["duplex"], purpose="rent"),
#         "-views",
#         bool(m["duplex"]),
#     ),
#     (
#         "sec_bungalows",
#         "Bungalows for Rent & Sale",
#         f"/properties/?property_type={m['bungalow']}",
#         dict(property_type_id=m["bungalow"]),
#         "-views",
#         bool(m["bungalow"]),
#     ),
#     (
#         "sec_mansion",
#         "Luxury Mansions in Abuja",
#         f"/properties/?property_type={m['mansion']}",
#         dict(property_type_id=m["mansion"]),
#         "-price",
#         bool(m["mansion"]),
#     ),
#     (
#         "sec_studio",
#         "Studio Apartments",
#         f"/properties/?property_type={m['studio']}",
#         dict(property_type_id=m["studio"]),
#         "-views",
#         bool(m["studio"]),
#     ),
#     (
#         "sec_rooms",
#         "Single Rooms for Rent",
#         f"/properties/?property_type={m['room']}&purpose=rent",
#         dict(property_type_id=m["room"], purpose="rent"),
#         "price",
#         bool(m["room"]),
#     ),
#     (
#         "sec_offices",
#         "Office Spaces in Abuja",
#         f"/properties/?property_type={m['office']}&purpose=rent",
#         dict(property_type_id=m["office"], purpose="rent"),
#         "-views",
#         bool(m["office"]),
#     ),
#     (
#         "sec_shops",
#         "Shops & Commercial Spaces",
#         f"/properties/?property_type={m['shop']}",
#         dict(property_type_id=m["shop"]),
#         "-views",
#         bool(m["shop"]),
#     ),
#     # ── By feature ───────────────────────────────────────────────────
#     (
#         "sec_furnished_rent",
#         "Fully Furnished Rentals",
#         "/properties/?furnished=true&purpose=rent",
#         dict(furnished=True, purpose="rent"),
#         "-views",
#         True,
#     ),
#     (
#         "sec_serviced",
#         "Serviced Apartments",
#         "/properties/?serviced=true",
#         dict(serviced=True),
#         "-views",
#         True,
#     ),
#     (
#         "sec_shared",
#         "Shared Apartments in Abuja",
#         "/properties/?shared=true&purpose=rent",
#         dict(shared=True, purpose="rent"),
#         "-views",
#         True,
#     ),
#     (
#         "sec_furnished_sale",
#         "Furnished Homes for Sale",
#         "/properties/?furnished=true&purpose=sale",
#         dict(furnished=True, purpose="sale"),
#         "-views",
#         True,
#     ),
#     # ── By price ─────────────────────────────────────────────────────
#     (
#         "sec_budget",
#         "Budget Rentals under ₦500,000/yr",
#         "/properties/?purpose=rent&max_price=500000",
#         dict(purpose="rent", price__lte=500000, rent_duration_months=12),
#         "price",
#         True,
#     ),
#     (
#         "sec_budget_monthly",
#         "Rentals under ₦50,000/month",
#         "/properties/?purpose=rent&max_price=50000",
#         dict(purpose="rent", price__lte=50000, rent_duration_months=1),
#         "price",
#         True,
#     ),
#     (
#         "sec_premium_sale",
#         "Premium Properties for Sale",
#         "/properties/?purpose=sale&min_price=50000000",
#         dict(purpose="sale", price__gte=50_000_000),
#         "-price",
#         True,
#     ),
#     (
#         "sec_mid_rent",
#         "Mid-Range Rentals (₦500k–₦2M/yr)",
#         "/properties/?purpose=rent&min_price=500000&max_price=2000000",
#         dict(purpose="rent", price__gte=500_000, price__lte=2_000_000, rent_duration_months=12),
#         "-views",
#         True,
#     ),
#     # ── By bedroom count ─────────────────────────────────────────────
#     (
#         "sec_1bed",
#         "1-Bedroom Apartments",
#         "/properties/?min_bedrooms=1&max_bedrooms=1",
#         dict(bedrooms=1),
#         "-views",
#         True,
#     ),
#     (
#         "sec_2bed",
#         "2-Bedroom Apartments",
#         "/properties/?min_bedrooms=2&max_bedrooms=2",
#         dict(bedrooms=2),
#         "-views",
#         True,
#     ),
#     (
#         "sec_3bed",
#         "3-Bedroom Homes",
#         "/properties/?min_bedrooms=3&max_bedrooms=3",
#         dict(bedrooms=3),
#         "-views",
#         True,
#     ),
#     (
#         "sec_4bed_plus",
#         "4+ Bedroom Family Homes",
#         "/properties/?min_bedrooms=4",
#         dict(bedrooms__gte=4),
#         "-views",
#         True,
#     ),
#     # ── Near schools ─────────────────────────────────────────────────
#     (
#         "sec_uniabuja",
#         "Housing near University of Abuja",
#         f"/properties/?school={m['uniabuja']}",
#         dict(school_id=m["uniabuja"]),
#         "-views",
#         bool(m["uniabuja"]),
#     ),
#     (
#         "sec_unn",
#         "Housing near University of Nigeria",
#         f"/properties/?school={m['unn']}",
#         dict(school_id=m["unn"]),
#         "-views",
#         bool(m["unn"]),
#     ),
#     (
#         "sec_bingham",
#         "Housing near Bingham University",
#         f"/properties/?school={m['bingham']}",
#         dict(school_id=m["bingham"]),
#         "-views",
#         bool(m["bingham"]),
#     ),
#     (
#         "sec_noun",
#         "Housing near NOUN",
#         f"/properties/?school={m['noun']}",
#         dict(school_id=m["noun"]),
#         "-views",
#         bool(m["noun"]),
#     ),
#     # ── Trending ─────────────────────────────────────────────────────
#     (
#         "sec_most_viewed",
#         "Most Viewed This Week",
#         "/properties/?sort=views",
#         dict(),
#         "-views",
#         True,
#     ),
#     (
#         "sec_newest",
#         "Newly Listed Properties",
#         "/properties/?sort=newest",
#         dict(),
#         "-created_at",
#         True,
#     ),
#     (
#         "sec_sale",
#         "Properties for Sale in Abuja",
#         "/properties/?purpose=sale",
#         dict(purpose="sale"),
#         "-views",
#         True,
#     ),
#     (
#         "sec_rent",
#         "All Rentals in Abuja",
#         "/properties/?purpose=rent",
#         dict(purpose="rent"),
#         "-views",
#         True,
#     ),
# ]

