# Generated by Django 6.0.2 on 2026-03-23 14:31

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import rentals.services.admin_message_service
import rentals.services.inquiry_service
import rentals.services.notification_service
import rentals.services.otp_service
import rentals.services.property_service
import rentals.services.user_service
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=30)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('alert', 'Alert'), ('maintenance', 'Maintenance')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_to_all', models.BooleanField(default=True, help_text='Show to all non-admin users')),
                ('show_to_agents', models.BooleanField(default=True)),
                ('show_to_tenants', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: Message will expire after this date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Admin Messages',
                'ordering': ['-created_at'],
            },
            bases=(rentals.services.admin_message_service.AdminMessageService, models.Model),
        ),
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True, help_text='How long have you been in real estate and in which areas?')),
                ('areas_of_focus', models.JSONField(blank=True, default=list, help_text='Which cities do they primarily operate in')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agent_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Application',
                'verbose_name_plural': 'Agent Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('preferred_purpose', models.CharField(blank=True, choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('has_seen_welcome', models.BooleanField(default=False)),
                ('has_shared_profile', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('other_phones', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.city')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssignedCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cities', to='rentals.agentprofile')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cities', to='rentals.city')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10, null=True)),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bedrooms_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('serviced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
            bases=(rentals.services.inquiry_service.InquiryService, models.Model),
        ),
        migrations.CreateModel(
            name='InquiryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_city', to='rentals.city')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_city', to='rentals.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='rentals.area')),
            ],
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.location'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_inquiry', 'New Inquiry'), ('inquiry_response', 'Inquiry Responded'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected'), ('application_reviewed', 'Agent Reviewed'), ('application_request', 'Agent Request'), ('agent_verified', 'Agent Verified'), ('new_visit_request', 'New Visit Request'), ('visit_confirmed', 'Visit Confirmed'), ('verification_request', 'verification_request')])),
                ('mode', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'Whatsapp'), ('phone', 'Phone')], default='email')),
                ('message', models.TextField()),
                ('related_id', models.CharField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(rentals.services.notification_service.NotificationService, models.Model),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(rentals.services.otp_service.OTPService, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='rentals.propertycategory')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('purpose', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('bedrooms', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rent_duration_months', models.PositiveIntegerField(blank=True, default=12, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('serviced', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rentals.agentprofile')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='rentals.location')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.propertytype')),
            ],
            bases=(rentals.services.property_service.PropertyService, models.Model),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.propertytype'),
        ),
        migrations.CreateModel(
            name='AgentPreferredTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_types', to='rentals.agentprofile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_types', to='rentals.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_listing', 'Fake / Misleading Listing'), ('harassment', 'Harassment / Abusive Behavior'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rentals.property')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('next_resumption_start', models.DateField(blank=True, null=True)),
                ('next_resumption_end', models.DateField(blank=True, null=True)),
                ('semester_end', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='rentals.location')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='rentals.school'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquires', to='rentals.school'),
        ),
        migrations.CreateModel(
            name='AgentAssignedSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_schools', to='rentals.agentprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_schools', to='rentals.school')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.state'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('tenant', 'Tenant/Looking to Rent'), ('agent', 'Real Estate Agent'), ('admin', 'Administrator')], default='tenant', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=255)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(rentals.services.user_service.UserProfileService, models.Model),
        ),
        migrations.CreateModel(
            name='InquiryAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_amenities', to='rentals.amenity')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_amenities', to='rentals.inquiry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('amenity', 'inquiry'), name='unique_inquiry_amenity')],
            },
        ),
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquires_responses', to='rentals.agentprofile')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquires_responses', to='rentals.inquiry')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquires_responses', to='rentals.property')),
            ],
            options={
                'indexes': [models.Index(fields=['inquiry'], name='rentals_inq_inquiry_94e9f9_idx'), models.Index(fields=['agent'], name='rentals_inq_agent_i_37a20d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='rentals.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='rentals.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('amenity', 'property'), name='unique_property_amenity')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.property')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['property'], name='rentals_pro_propert_f91db1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='rentals.property')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Property Visits',
                'ordering': ['-visit_date'],
                'unique_together': {('visitor', 'property', 'visit_date')},
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='rentals.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='rentals_sav_user_id_eeedf4_idx'), models.Index(fields=['property'], name='rentals_sav_propert_6b155b_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['short_name'], name='rentals_sch_short_n_7b2dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='rentals_sch_name_12dfc1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['purpose', 'status'], name='rentals_pro_purpose_dfc7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='rentals_pro_propert_e5b266_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='rentals_pro_price_a9c5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='rentals_pro_bedroom_1998d4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured'], name='rentals_pro_is_feat_e0b315_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['views'], name='rentals_pro_views_eb3277_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='rentals_pro_created_9311ae_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at', '-id'], name='rentals_pro_created_4069c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='rentals_pro_status_06bb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['school'], name='rentals_pro_school__d76ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['created_at'], name='rentals_inq_created_6d1895_idx'),
        ),
    ]
