# Generated by Django 6.0.2 on 2026-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
