# Generated by Django 6.0.2 on 2026-03-05 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inquiry', 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='Inquiry',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='bathrooms_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='bathrooms_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='bedrooms_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='bedrooms_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='budget_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='budget_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('shop', 'Shop'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('land', 'Land'), ('studio', 'Studio'), ('commercial', 'Commercial Building')], max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='purpose',
            field=models.CharField(blank=True, choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inquires', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('fake_listing', 'Fake / Misleading Listing'), ('harassment', 'Harassment / Abusive Behavior'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant/Looking to Rent'), ('agent', 'Real Estate Agent')], default='tenant', max_length=10),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at', '-id'], name='rentals_pro_created_4069c2_idx'),
        ),
    ]
