# Generated by Django 6.0.2 on 2026-02-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_payment_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=20)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='rentals.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
