# Generated by Django 4.2.10 on 2026-01-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
