# Generated by Django 6.0.2 on 2026-02-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_paymentaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('shop', 'Shop'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('land', 'Land'), ('studio', 'Studio'), ('commercial', 'Commercial Building')], max_length=20),
        ),
    ]
