# Generated by Django 4.2.10 on 2026-01-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_userprofile_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant/Looking to Rent'), ('owner', 'Property Owner/Landlord')], default='tenant', max_length=10),
        ),
    ]
