# Generated by Django 6.0.2 on 2026-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_property_images_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_5',
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
