# Generated by Django 4.2.10 on 2026-01-10 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant/Looking to Rent'), ('owner', 'Property Owner/Landlord'), ('student', 'Student')], default='tenant', max_length=10),
        ),
        migrations.CreateModel(
            name='StudentProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('self_contain', 'Self Contain')], max_length=20)),
                ('purpose', models.CharField(choices=[('rent', 'For Rent')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review')], default='draft', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_duration_months', models.IntegerField(blank=True, choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year')], null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='properties/main/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='properties/additional/')),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_properties_created', to=settings.AUTH_USER_MODEL)),
                ('rented_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_rented_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Property',
                'verbose_name_plural': 'Student Properties',
                'db_table': 'student_property',
                'ordering': ['-created_at'],
            },
        ),
    ]
