# Generated by Django 6.0.2 on 2026-02-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_property_image_1_remove_property_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
