# Generated by Django 6.0.2 on 2026-02-15 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_property_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['purpose', 'city', 'status'], name='rentals_pro_purpose_e2036d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='rentals_pro_propert_427152_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='rentals_pro_price_a9c5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='rentals_pro_bedroom_1998d4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured'], name='rentals_pro_is_feat_e0b315_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['views'], name='rentals_pro_views_eb3277_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='rentals_pro_created_9311ae_idx'),
        ),
    ]
