# Generated by Django 4.2.10 on 2026-01-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_userprofile_user_type_studentproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproperty',
            name='university',
            field=models.CharField(blank=True, choices=[('university_of_abuja', 'University of Abuja'), ('nigerian_defence_academy', 'Nigerian Defence Academy'), ('other', 'Other')], help_text='Nearest property to the university.', max_length=50, null=True),
        ),
    ]
