# Generated by Django 6.0.2 on 2026-02-19 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_property_rentals_pro_purpose_e2036d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['purpose', 'status'], name='rentals_pro_purpose_dfc7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='rentals_pro_status_06bb1a_idx'),
        ),
    ]
