# Generated by Django 4.2.10 on 2026-01-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_studentproperty_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproperty',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('available', 'Available'), ('rented', 'Rented')], default='draft', max_length=20),
        ),
    ]
