# Generated by Django 4.2.10 on 2026-01-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0008_alter_studentproperty_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPropertyRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rentals', to='rentals.studentproperty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tenant_rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Property Rental',
                'verbose_name_plural': 'Student Property Rentals',
                'ordering': ['-created_at'],
            },
        ),
    ]
